# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk

    working_directory: ~/project

    environment:
      JAVA_TOOL_OPTIONS: -Xmx2G -Djava.security.egd=file:/dev/./urandom -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Configure
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.warning.mode=none" > ~/.gradle/gradle.properties


      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CIRCLE_JOB}}-{{ checksum "build.gradle" }}
            - dependencies-{{ .Environment.CIRCLE_JOB}}-
            - dependencies-

      # run tests!
      - run:
          name: Run Tests
          command: |
            chmod +x ./gradlew
            ./gradlew -PverboseTests=true test jacocoTestReport

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: dependencies-{{ .Environment.CIRCLE_JOB}}-{{ checksum "build.gradle" }}


workflows:
  version: 2
  on_commit:
    jobs:
      - build